name: Build and Deploy to Azure

on:
  push:
    branches:
      - master  # Hoặc nhánh chính bạn muốn triển khai

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build . -t <dockerhub_username>/<image_name>:latest
        docker push <dockerhub_username>/<image_name>:latest

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: '<azure-app-service-name>'
        images: '<dockerhub_username>/<image_name>:latest'
